package com.kandanda.scoreboard;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for the Scoreboard.
 *
 * <p>Every expected value here is computed BY HAND in the comments, not generated by
 * the code under test. That is the whole point: we must trust the judge before we
 * trust any contestant. If these pass, the metric is correct.
 */
class CalibrationServiceTest {

    private final CalibrationService service = new CalibrationService();
    private static final double TOL = 1e-9;

    @Test
    void perfectConfidentPredictionScoresZero() {
        // Predict 1.0 that an event happens, and it happens.
        // Brier = (1.0 - 1.0)^2 = 0.  Log-loss = -ln(1.0) = 0 (after clamp, ~0).
        var preds = List.of(Prediction.withoutMarket("certain hit", 1.0, true));
        var report = service.score(preds);

        assertEquals(0.0, report.brier(), TOL);
        // clamp pulls 1.0 to 1-1e-15, so log-loss is ~1e-15, effectively 0.
        assertEquals(0.0, report.logLoss(), 1e-12);
    }

    @Test
    void coinFlipScoresQuarterOnBrier() {
        // The famous baseline: always predict 0.5.
        // Brier per prediction = (0.5 - actual)^2 = 0.25 regardless of outcome.
        // Any useful model must beat 0.25.
        var preds = List.of(
                Prediction.withoutMarket("a", 0.5, true),
                Prediction.withoutMarket("b", 0.5, false),
                Prediction.withoutMarket("c", 0.5, true)
        );
        var report = service.score(preds);

        assertEquals(0.25, report.brier(), TOL);
        // Log-loss for p=0.5 is -ln(0.5) = 0.6931471805599453 every time.
        assertEquals(0.6931471805599453, report.logLoss(), TOL);
    }

    @Test
    void brierMatchesHandComputation() {
        // Two predictions, worked out by hand:
        //  1) predict 0.7, event happens (actual=1): (0.7-1)^2 = 0.09
        //  2) predict 0.2, event does NOT happen (actual=0): (0.2-0)^2 = 0.04
        // mean Brier = (0.09 + 0.04) / 2 = 0.065
        var preds = List.of(
                Prediction.withoutMarket("hit", 0.7, true),
                Prediction.withoutMarket("correct lowball", 0.2, false)
        );
        var report = service.score(preds);

        assertEquals(0.065, report.brier(), TOL);
    }

    @Test
    void logLossPunishesConfidentWrong() {
        // Predict 0.99 that event happens, but it does NOT.
        // prob assigned to truth = 1 - 0.99 = 0.01;  -ln(0.01) = 4.605170185988091
        var preds = List.of(Prediction.withoutMarket("arrogant miss", 0.99, false));
        var report = service.score(preds);

        assertEquals(4.605170185988091, report.logLoss(), TOL);
        // Brier for the same: (0.99 - 0)^2 = 0.9801
        assertEquals(0.9801, report.brier(), TOL);
    }

    @Test
    void beatsMarketWhenOurBrierIsLower() {
        // We predict 0.8 (event happens) -> Brier (0.8-1)^2 = 0.04
        // Market implied 0.6           -> Brier (0.6-1)^2 = 0.16
        // We beat the market.
        var preds = List.of(new Prediction("value spot", 0.8, 0.6, true));
        var report = service.score(preds);

        assertEquals(0.04, report.brier(), TOL);
        assertEquals(0.16, report.marketBrier(), TOL);
        assertTrue(report.beatsMarket());
    }

    @Test
    void marketBrierIsNaNWhenNoMarketData() {
        var preds = List.of(Prediction.withoutMarket("no market", 0.5, true));
        var report = service.score(preds);

        assertTrue(Double.isNaN(report.marketBrier()));
        assertFalse(report.beatsMarket());
    }

    @Test
    void emptyOrNullThrows() {
        assertThrows(IllegalArgumentException.class, () -> service.score(List.of()));
        assertThrows(IllegalArgumentException.class, () -> service.score(null));
    }

    @Test
    void rejectsOutOfRangeProbability() {
        assertThrows(IllegalArgumentException.class,
                () -> Prediction.withoutMarket("bad", 1.5, true));
        assertThrows(IllegalArgumentException.class,
                () -> new Prediction("bad market", 0.5, -0.1, true));
    }
}
